project:
  type: website

website:
  title: "CMPSC 302"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - syllabus/index.qmd
      - schedule/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



