[build]
  command = "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.tar.gz && tar -xvzf quarto-1.3.450-linux-amd64.tar.gz && sudo mv quarto-1.3.450/bin/* /usr/local/bin/ && quarto render"
  publish = "_site"

[build.environment]
  NODE_VERSION = "16"
